# Generated by Django 5.0.1 on 2024-01-19 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='date collected')),
                ('air_tank_1', models.IntegerField(default=0)),
                ('air_tank_2', models.IntegerField(default=0)),
                ('rpm', models.IntegerField(default=0)),
                ('speed', models.IntegerField(default=0)),
            ],
        ),
    ]
